import { Router } from 'express';
import { healthRoutes } from './health.routes';
import { authRoutes } from '../modules/auth/routes/auth.routes';
import { onboardingRoutes } from '../modules/onboarding/routes/onboarding.routes';
import { dashboardRoutes } from '../modules/dashboard/routes/dashboard.routes';
import { roadmapRoutes } from '../modules/roadmap/routes/roadmap.routes';
import { studyPlanRoutes } from '../modules/study-plan/routes/study-plan.routes';
import { progressRoutes } from '../modules/progress/routes/progress.routes';
import { gapReportRoutes } from '../modules/gap-report/routes/gap-report.routes';
import { recommendationRoutes } from '../modules/recommendation/routes/recommendation.routes';
import { mentorRoutes } from '../modules/mentor/routes/mentor.routes';
import { codingRoutes } from '../modules/coding/routes/coding.routes';
import { executionRoutes } from '../modules/execution/routes/execution.routes';
import { judgeRoutes } from '../modules/judge/routes/judge.routes';
import { submissionRoutes } from '../modules/submission/routes/submission.routes';
import { codeReviewRoutes } from '../modules/code-review/routes/code-review.routes';
import { assessmentRoutes } from '../modules/assessment/routes/assessment.routes';
import { interviewRoutes } from '../modules/interview/routes/interview.routes';
import { contestRoutes } from '../modules/contest/routes/contest.routes';
import { leaderboardRoutes } from '../modules/leaderboard/routes/leaderboard.routes';
import { placementRoutes } from '../modules/placement/routes/placement.routes';
import { careerRoutes } from '../modules/career/routes/career.routes';
import { jobsRoutes } from '../modules/jobs/routes/jobs.routes';
import { internshipsRoutes } from '../modules/internships/routes/internships.routes';
import { applicationsRoutes } from '../modules/applications/routes/applications.routes';
import { resumeAnalyzerRoutes } from '../modules/resume-analyzer/routes/resume-analyzer.routes';
import { resumeRoutes } from '../modules/resume/routes/resume.routes';
import { portfolioRoutes } from '../modules/portfolio/routes/portfolio.routes';
import { coverLetterRoutes } from '../modules/cover-letter/routes/cover-letter.routes';
import { jobRecommendationRoutes } from '../modules/job-recommendation/routes/job-recommendation.routes';
import { notesRoutes } from '../modules/notes/routes/notes.routes';
import { bookmarksRoutes } from '../modules/bookmarks/routes/bookmarks.routes';
import { resourcesRoutes } from '../modules/resources/routes/resources.routes';
import { revisionRoutes } from '../modules/revision/routes/revision.routes';
import { knowledgeRoutes } from '../modules/knowledge/routes/knowledge.routes';
import { adminRoutes } from '../modules/admin/routes/admin.routes';
import { universeRoutes } from '../modules/universe/routes/universe.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/roadmap', roadmapRoutes);
router.use('/study-plan', studyPlanRoutes);
router.use('/progress', progressRoutes);
router.use('/gap-report', gapReportRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/mentor', mentorRoutes);
router.use('/coding', codingRoutes);
router.use('/code', executionRoutes);
router.use('/code', judgeRoutes);
router.use('/code', codeReviewRoutes);
router.use('/submissions', submissionRoutes);
router.use('/assessment', assessmentRoutes);
router.use('/interview', interviewRoutes);
router.use('/contest', contestRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/placement', placementRoutes);
router.use('/career', careerRoutes);
router.use('/jobs', jobsRoutes);
router.use('/internships', internshipsRoutes);
router.use('/applications', applicationsRoutes);
router.use('/resume', resumeRoutes);
router.use('/resume', resumeAnalyzerRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/cover-letter', coverLetterRoutes);
router.use('/job-recommendations', jobRecommendationRoutes);
router.use('/notes', notesRoutes);
router.use('/bookmarks', bookmarksRoutes);
router.use('/resources', resourcesRoutes);
router.use('/revision', revisionRoutes);
router.use('/knowledge', knowledgeRoutes);
router.use('/admin', adminRoutes);
router.use('/universe', universeRoutes);
router.use('/galaxy', universeRoutes);
router.use('/current-mission', universeRoutes);
router.use('/mission', universeRoutes);

export const v1Routes = router;
